### PR TITLE
Fix #386

### LINKED ISSUE #386: Latitude & Longitude Missing from Punjab (PB), State in India
Latitude and Longitude are missing from CSV, and JSON Files.

### PR DESCRIPTION
**Pull request by ZenithClown**
* lat-lon is available in SQL file, and all values are updated with the same value

### CODE REVIEW

**Comment by dr5hn** [comment]
@ZenithClown Thanks for the PR. 🎉 

However, Please follow https://github.com/dr5hn/countries-states-cities-database/blob/master/.github/CONTRIBUTING.md for fixing the issue.

**Comment by ZenithClown** [comment]
@dr5hn, as I've mentioned in the commit message the said latitude and longitude value, is already present in `sql/states.sql` and `sql/world.sql`. However, the same is not updated in other raw files - like CSV and JSON.

About labeling, I'm not able to provide a `label` to my issue #386

**Comment by dr5hn** [comment]
@ZenithClown I see it empty in `states.sql`

**Comment by dr5hn** [comment]
@ZenithClown Anyways added to states.sql now! Thanks for reporting.

**Pull request closed without merging**
