### PR TITLE
Fix some Chinese names and add wikidata IDs.

### PR DESCRIPTION
**Pull request by sun-jiao**

### CODE REVIEW

**Comment by dr5hn** [comment]
@sun-jiao Thanks for your contribution on this. Could you kindly transfer the amendments made in `world.sql` and exclude the changes made in `countries.sql` and `states.sql`?

**Review by dr5hn — CHANGES_REQUESTED** [review]
@sun-jiao Thanks for your contribution on this. Could you kindly transfer the amendments made in world.sql and exclude the changes made in countries.sql and states.sql?

**Comment by sun-jiao** [comment]
@dr5hn Do you mean changes should be made to world.sql rather than countries.sql and states.sql?

**Comment by dr5hn** [comment]
@sun-jiao Yes exactly. Please refer https://github.com/dr5hn/countries-states-cities-database/blob/master/.github/CONTRIBUTING.md

**Comment by sun-jiao** [comment]
@dr5hn OK. I'll do it in recent days.

**Comment by sun-jiao** [comment]
@dr5hn In fact, I forgot what changes I made, and I'm not sure how to view the differences in huge files. So it might take more time to do it.

**Pull request closed without merging**
