### PR TITLE
Italian fix

### PR DESCRIPTION
**Pull request by ionecum**
Primary divisions in Italy are "regions", not "provinces". A province in Italy is just a city and it is the capital of the region, just like Sacramento is the capital of California. Therefore if you define a city like "Milan" like a province, it will be then duplicate as a city of Lombardy. And you end up with lot of duplicated data. I fixed them. Below the changelog of this commit. I would like to be a contrubutor of this project. And I would agree if you accept this commit.

And check the project. You might have made the same mistake with other countries not only Italy. For example, Brazil is a very problematic one.

Here the changelog:
Rome is not a province. Is a city. Removed id 1711 (Duplicate)
Milan is not a province. Is a city. Removed id 1698 (Duplicate)
Modena is not a province. Is a city. Removed id 1757 (Duplicate)
Messina is not a province. Is a city. Removed id 1770 (Duplicate)
Matera is not a province. Is a city. Removed id 1760 (Duplicate)
Bari is not a province. Is a city. Removed id 1772 (Duplicate)
Ascoli Piceno is not a province. Is a city. Removed id 1681 (Duplicate)
Same thing with Asti. Removed id 1780 (Duplicate)
Agrigento id 1727
Alessandria id 1783
Ancona 1672
Barletta-Adria-Trani 1686
Latina 1674
Lecce 1675
Lecco 1677
Livorno 1745
Lodi 1747
Lucca 1749
Macerata 1750
Medio Campidiano 1761
Massa and Carrara 1759
Monza and Brianza 1769
Cagliari 1682
Belluno 1689
Benevento 1701
Bergamo 1704
Biella 1778
Brindisi 1714
Bologna 1684
Brescia 1717
Caltanissetta 1718
Campobasso 1721
Caserta 1731
Catania 1766
Catanzaro 1728
Chieti 1739
Como 1740
Cosenza 1742
Cremona 1751
Crotone 1754
Cuneo 1775
Enna 1723
Fermo 1744
Ferrara 1746
Foggia 1771
Florence 1680
Forlì-Cesena 1779
Frosinone 1776
Genoa 1699
Gorizia 1777
Grosseto 1787
Imperia 1788
Isernia 1789
L'Aquila 1781
La Spezia 1791
Mantua 1758
Naples 1724
Novara 1774
Nuoro 1790
Oristano 1786
Padua 1665
Palermo 1668
Parma 1666
Pavia 1676
Perugia 1691
Pesaro And Urbino 1693
Pescara 1694
Piacenza 1696
Pisa 1685
Pistoia 1687
Pordenone 1690
Potenza 1697
Prato 1700
Ragusa 1729
Reggio Calabria 1671
Reggio Emilia 1708
Rieti 1712
Rimini 1713
Rovigo 1719
Salerno 1720
Sassari 1722
Savona 1732
Siena 1734
Siracusa 1667
Sondrio 1741
South Sardinia (This is not a province) 1730
South Tyrol 1767 (This is not a province)
Taranto 1743
Teramo 1752
Terni 1755
Trapani 1733
Trentino 1748 (Same thing as Trentino-South Tyrol)
Treviso 1762
Trieste 1763
Turin 1710
Udine 1764
Varese 1765
Venice 1673
Verbano-Cussio-Ossola 1726
Vercelli 1785
Verona 1736
Vibo Valentia 1737
Vicenza 1738
Viterbo 1735

I also made several new commits removing another 3 "wrong provinces". 
Avellino 1692
Sondrio 1741
Terni 1755

### CODE REVIEW

**Comment by dr5hn** [comment]
Hi, @ionecum Thanks for your hard work on this.

The files which you've edited, are being auto-generated by themselves.

You just need to make edits in the `world.sql` file.

Can you please do that for me?

**Comment by dr5hn** [comment]
@ionecum Can you please follow https://github.com/dr5hn/countries-states-cities-database/blob/master/.github/CONTRIBUTING.md and make the updates in `world.sql` That would be appreciated.

**Comment by dr5hn** [comment]
tagging issue #500 

@ionecum If you want, I can work on this and will convert it into `world.sql`.

**Comment by ionecum** [comment]
Hello, 
I think I already did it. I modified the world database according to the guidelines, I remember having already read them. Please check. And tell me if otherwise.

**Comment by dr5hn** [comment]
@ionecum 
In file changes, I can't see the world.sql file.

Screenshot 2022-10-05 at 2 30 03 PM

**Comment by ionecum** [comment]
Please ignore the changes to csv files or vendor/base.php. I had to change base.php in order to make the script work locally, but I have restored it in its original state. And the other changes are just tests. 
The important change I've made, it was on world.sql, maybe you can't find it because it is aready committed in the branch I have uploaded. Please check it, as you can see here:

MariaDB [world]> select id, name from states where country_id=107;
+------+-----------------------+
| id   | name                  |
+------+-----------------------+
| 1664 | Tuscany               |
| 1669 | Campania              |
| 1670 | Marche                |
| 1678 | Lazio                 |
| 1679 | Abruzzo               |
| 1683 | Umbria                |
| 1688 | Apulia                |
| 1695 | Molise                |
| 1702 | Piedmont              |
| 1703 | Calabria              |
| 1705 | Lombardy              |
| 1706 | Basilicata            |
| 1707 | Ravenna               |
| 1709 | Sicily                |
| 1715 | Sardinia              |
| 1716 | Aosta Valley          |
| 1725 | Trentino-South Tyrol  |
| 1753 | Veneto                |
| 1756 | Friuli?Venezia Giulia |
| 1768 | Liguria               |
| 1773 | Emilia-Romagna        |
+------+-----------------------+
21 rows in set (0.008 sec)

**Comment by ionecum** [comment]
I only changed the generated for testing purposes, while in vendor/base.php I only temprarly changed it to make it work on my local machine. 
None of these changes is important. I also committed and pushed the world.sql again, maybe last time it was not pushed properly. 
It should work now.

**Review by ionecum — COMMENTED** [review]
I just pushed this file again.

**Comment by ionecum** [comment]
Hello, 
I fixed the problem weeks ago. Now the sql is updated and fully working. 
Could you please take any action?

**Comment by dr5hn** [comment]
@ionecum Thanks for the reminder. Sorry, I am running a bit busy and on holiday here. I didn't get a chance to look at it.

Ok, I have created another PR with clean world.sql so that I can understand changes. But I am able to do the review next weekend only.

https://github.com/dr5hn/countries-states-cities-database/pull/531

**Comment by ionecum** [comment]
Hello, as I told you in a message, Modena, Messina, Matera, etc are not provinces in the sense of primary divisions. In Italy a province is just a capital city. By keeping your current data as it was, you are doing a mistake. Ask to any Italian, ONLY REGIONS are primary divisions.

**Comment by ionecum** [comment]
Hello,
you have not answered my issue but it seems you have a similar problem
with several countries.

1. United Kingdom has no cities in your database, London is a city,
the boroughs of London are neighborhoods, not states.

2. Even with France, Paris is not a province, it's a city. Then you
have another Paris in Ile de France province, this latter being the
one in the right place.

But the big problem is that I have duplicate data
Paris and no cities
Ile de France and Paris

I think I should consider searching for another database, yours is not
reliable enough.

Sincerely
DR

**Comment by dr5hn** [comment]
@ionecum I've re-reviewed your updates and found them correct, I will update them soon. I am a bit tied up with personal chores, so I am not getting enough time to fix these issues.

Thanks for letting me know about the other issues.
1. UK ones are known issues
2. I will take a look at France's issue

Btw apart from UK and France, do you see similar anomalies with any other countries?

Also, if you can find a reliable source, please let me know. So that I can make this DB reliable enough for everyone.

Thanks so much for all of your efforts so far.

**Pull request closed without merging**
