### PR TITLE
add: regions database table

### PR DESCRIPTION
**Pull request by Freelenzer**
This add first implementation of region/continents

i will add a PR for Subregions later.

What else needs to be done here?

What can we add to regions? Timezones?

### CODE REVIEW

**Comment by dr5hn** [comment]
@Freelenzer Thank you for your hard work on this! I really appreciate it.

Can we please keep the region and subregion columns as is so they stay backwards compatible?

Also, can you please migrate the updates of the `regions`, `subregions` table and `countries` table within `world.sql`?

The JSON, CSV, XML & YAML formats will get autogenerated once this PR is merged. You don't have to worry about them.

**Comment by dr5hn** [comment]
@Freelenzer  Can you please migrate the updates of the regions, subregions table and countries table within world.sql?

**Comment by Freelenzer** [comment]
Yes Im on it 👍
Was just disrupted this morning 🌅

**Comment by Freelenzer** [comment]
@dr5hn  changes are commited now :)

**Comment by dr5hn** [comment]
@Freelenzer Thanks for that! Can you please remove the `countries.sql` file updates? That file will be automatically generated.

**Review by dr5hn — APPROVED** [review]

**Pull request merged**
