### PR TITLE
fix the bug in cities sql file

### PR DESCRIPTION
**Pull request by mitesh000790**
Address:- #109 

fix the bug in cities.sql file

### CODE REVIEW

**Comment by dr5hn** [comment]
@mitesh000790 Read the [Contribution Guidelines](https://github.com/dr5hn/countries-states-cities-database/blob/master/CONTRIBUTING.md) carefully.

You need to also make an update to `world.sql`.

**Comment by mitesh000790** [comment]
@dr5hn okay thanks

**Comment by dr5hn** [comment]
@mitesh000790 Can you please allow me to make edits on this ? https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork
image

**Comment by mitesh000790** [comment]
I have already given permission

Screenshot from 2020-10-04 15-15-53

**Review by dr5hn — APPROVED** [review]

**Pull request merged**
