### PR TITLE
Add Baghdad cities

### PR DESCRIPTION
**Pull request by abdo0**
After rebase from master a new edit to cities.

### CODE REVIEW

**Comment by dr5hn** [comment]
@abdo0 Can you please use PHPMyAdmin for dumping? Diff is too long.

**Comment by abdo0** [comment]
@dr5hn Thanks for the reply 

Dump took it through Mysql workbench

**Comment by dr5hn** [comment]
@abdo0 Still the same. Last time it was showing precise updates.

Oh I see, you made edits to `cities.sql`
Instead, it should be in the `world.sql`

```
(153202,'Adamiyah',3959,'BG',104,'IQ',33.36917800,44.33955940,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153203,'Al Adel',3959,'BG',104,'IQ',33.35912830,44.28138680,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153204,'Al Baladiyat',3959,'BG',104,'IQ',33.34931610,44.41071530,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153205,'Al Jamaa',3959,'BG',104,'IQ',33.34114470,44.34062690,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153206,'Al Saadoon Park',3959,'BG',104,'IQ',33.32480360,44.41470980,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153207,'Al Salhiah',3959,'BG',104,'IQ',33.32254010,44.38425050,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153208,"Al Za'franiya",3959,'BG',104,'IQ',33.31857750,44.48686390,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153209,'Al-Ubaidi',3959,'BG',104,'IQ',33.32036030,44.45955910,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153210,'Al-Wahda',3959,'BG',104,'IQ',33.31115820,44.43352280,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153211,'Ameria',3959,'BG',104,'IQ',33.29671020,44.27076790,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153212,'Amil District',3959,'BG',104,'IQ',33.27606090,44.31037170,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153213,'Amin',3959,'BG',104,'IQ',33.31248740,44.48634150,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153214,'Arasat AlHindiya',3959,'BG',104,'IQ',33.29335790,44.42302450,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153215,'At Taifiya',3959,'BG',104,'IQ',33.35643940,44.35791100,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153216,'Bab Al Moatham',3959,'BG',104,'IQ',33.36014170,44.36507700,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153217,'Bab Al Sharqi',3959,'BG',104,'IQ',33.33249060,44.41407910,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153218,'Baghdad Al Jadeeda',3959,'BG',104,'IQ',33.31335440,44.47157920,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153219,'Baijai',3959,'BG',104,'IQ',33.33254000,44.34509550,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153220,'Bataween',3959,'BG',104,'IQ',33.32112350,44.40855680,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153221,'Bayaa',3959,'BG',104,'IQ',33.28255440,44.37528030,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153222,'Binouk',3959,'BG',104,'IQ',33.39278120,44.41114480,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153223,"Bo'aitha",3959,'BG',104,'IQ',33.24194630,44.42695090,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153224,'Camp Sarah',3959,'BG',104,'IQ',33.30112930,44.44469600,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153225,'Daoudi',3959,'BG',104,'IQ',33.31214030,44.32584820,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153226,'Dora',3959,'BG',104,'IQ',33.23126860,44.36198120,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153227,'Ghadeer',3959,'BG',104,'IQ',33.33749740,44.46281840,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153228,'Ghazaliya',3959,'BG',104,'IQ',33.34143530,44.22354420,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153229,"Gherai'at",3959,'BG',104,'IQ',33.39208370,44.30443140,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153230,'Green Zone',3959,'BG',104,'IQ',33.31376100,44.35900560,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153231,'Habibiya',3959,'BG',104,'IQ',33.33920270,44.46846120,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153232,'Harthiya',3959,'BG',104,'IQ',33.22626120,44.39826750,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153233,'Hurriya',3959,'BG',104,'IQ',33.34241870,44.30656300,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153234,'Iskan',3959,'BG',104,'IQ',33.33405930,44.32303100,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153235,'Jadriyah',3959,'BG',104,'IQ',33.26076360,44.41117200,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153236,'Jamila',3959,'BG',104,'IQ',33.35108840,44.41495600,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153237,'Jihad',3959,'BG',104,'IQ',33.25289200,44.29231180,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153238,'Kadhimiya',3959,'BG',104,'IQ',33.38129610,44.35139180,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153239,'Kamaliyah',3959,'BG',104,'IQ',33.35008480,44.50894110,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153240,'Karada',3959,'BG',104,'IQ',33.29336610,44.39641530,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153241,'Khadra',3959,'BG',104,'IQ',33.31972470,44.28764700,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153242,'Mansour',3959,'BG',104,'IQ',33.31422960,44.33631230,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153243,'Mashtal',3959,'BG',104,'IQ',33.32443210,44.49314830,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153244,'Mustansiriya',3959,'BG',104,'IQ',33.36298920,44.38695430,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153245,'Qadisiyah',3959,'BG',104,'IQ',33.32719630,44.31623840,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153246,'Sadr City',3959,'BG',104,'IQ',33.37692330,44.40446380,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153247,'Saidiya',3959,'BG',104,'IQ',33.26500930,44.33159340,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153248,"Sha'ab",3959,'BG',104,'IQ',33.41309100,44.38611030,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153249,'Sheik Maaruf',3959,'BG',104,'IQ',33.33896010,44.34789580,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153250,'Shorjah',3959,'BG',104,'IQ',33.34613940,44.39504420,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153251,'Suleikh',3959,'BG',104,'IQ',33.39343320,44.36144500,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153252,'Ur District',3959,'BG',104,'IQ',33.41694000,44.39060790,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153253,'Wazireya',3959,'BG',104,'IQ',33.36366170,44.38196550,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153254,'Yarmouk',3959,'BG',104,'IQ',33.33938360,44.32212520,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL),
(153255,'Ziyouna',3959,'BG',104,'IQ',33.32484340,44.45454600,'2022-08-31 07:02:38','2022-08-31 07:02:38',1,NULL);
```

**Comment by abdo0** [comment]
@dr5hn OK I WILL

**Comment by dr5hn** [comment]
@abdo0 Perfect. Thank you so much.

**Review by dr5hn — APPROVED** [review]

**Comment by abdo0** [comment]
@dr5hn Thank you too.

**Pull request merged**
