### PR TITLE
feat: Add Postgres database migration and export action

### PR DESCRIPTION
**Pull request by agostinofiscale**
Hi everyone!

I needed the countries-states-cities-database for Supabase that uses Postgres but of course the SQL was not working. So i found out a way to migrate datas from MySQL to Postgres using a third-party software called pgloader.

I thought to make this because of course there will be changes and maybe someone else can use this as well.

I downgraded MySQL to 5.7 because the 8 uses a different authentication system that pgloader doesn't support, it doesn't seems to break something but maybe you will see something that I don't see.

### CODE REVIEW

**Comment by dr5hn** [comment]
@agostinofiscale Awesome 🔥 

Is there a way we can test the action before merging it?

**Comment by agostinofiscale** [comment]
Hi @dr5hn,

I started an action and as you can see it worked well, the only problem was for the pull request because the reviewers are not collaborators in my fork. 

Tell me If i can help in some way!

**Comment by dr5hn** [comment]
@agostinofiscale But i see those psql files empty.

**Comment by agostinofiscale** [comment]
@dr5hn check out the PR generated in my fork

**Comment by dr5hn** [comment]
@agostinofiscale Thanks i can see that now! Btw any reason behind using mysql 5.7 instead of 8?

**Comment by agostinofiscale** [comment]
@dr5hn Yep

> I downgraded MySQL to 5.7 because the 8 uses a different authentication system that pgloader doesn't support, it doesn't seems to break something but maybe you will see something that I don't see.

**Review by dr5hn — APPROVED** [review]

**Comment by dr5hn** [comment]
@agostinofiscale Once more, I want to express my heartfelt gratitude for your valuable contribution. 🍻

**Pull request merged**
