### PR TITLE
New Luanda citties

### PR DESCRIPTION
**Pull request by NzongoPedro**
**@aoscode
Team: Debugers**

The map of Angola has undergone changes so I added new cities for the province of Luanda, Cacuaco, Viana, Talatona and Cazenga

### CODE REVIEW

**Comment by NzongoPedro** [comment]
> **@aoscode
> Team: Debugers**
> 
> The map of Angola has undergone changes so I added new cities for the province of Luanda, Cacuaco, Viana, Talatona and Cazenga

@dr5hn

**Review by NzongoPedro — COMMENTED** [review]
Please, if not exit ; on line 151289, you can add.
Was add new cittien of Luanda

**Comment by dr5hn** [comment]
@NzongoPedro Got your changes merged in #713

**Comment by sombo20** [comment]
@Afranioalves

**Comment by sombo20** [comment]
@aosccode

**Comment by sombo20** [comment]
@aosccode

**Comment by sombo20** [comment]
@aosccode

**Pull request closed without merging**
