### PR TITLE
Add hedehusene, denmark

### LINKED ISSUE #681: Missing Hedehusene, Denmark
Town in Capital Region of Denmark, population 15k. https://www.wikidata.org/wiki/Q2248624

### PR DESCRIPTION
**Pull request by scottgigante**
Closes #681

### CODE REVIEW

**Comment by dr5hn** [comment]
@scottgigante Thank you for the pull request (PR)! Your contribution is greatly appreciated.

Could you kindly perform a branch rebase, please?

**Comment by scottgigante** [comment]
Done, thanks!

**Comment by dr5hn** [comment]
Closing, because Changes were merged in #684

**Comment by dr5hn** [comment]
@scottgigante I'm interested in understanding what steps someone would need to follow to transition from a career in web development to a field like machine learning or a related data discipline.

**Comment by dr5hn** [comment]
@scottgigante Thank you for your willingness to chat! I appreciate it. I'll send you a connection request shortly, and we can continue our conversation there.

**Pull request closed without merging**
