### PR TITLE
Update Macedonia to North Macedonia

### PR DESCRIPTION
**Pull request by bor0**
In 2019 with the [Prespa Agreement](https://en.wikipedia.org/wiki/Prespa_Agreement) the country name was changed

cc @dr5hn

### CODE REVIEW

**Comment by dr5hn** [comment]
@bor0 Thanks for the fixes! Can you please delete all other file updates and keep the `world.sql` changes?

Because all other files are auto generated.

**Comment by bor0** [comment]
@dr5hn thanks, PR updated. Would be great to have that as information somewhere in the README.md, for future contributors.

**Comment by dr5hn** [comment]
@bor0 You might have missed looking at [Contribution Guidelines](https://github.com/dr5hn/countries-states-cities-database/blob/master/.github/CONTRIBUTING.md)

**Review by dr5hn — APPROVED** [review]

**Comment by bor0** [comment]
> @bor0 You might have missed looking at [Contribution Guidelines](https://github.com/dr5hn/countries-states-cities-database/blob/master/.github/CONTRIBUTING.md)

Thanks! I have :)

Still would probably be useful to include a link to it in README.md, so that nobody can miss it :)

**Pull request merged**
