### PR TITLE
fix: added jamtland county for sweden

### PR DESCRIPTION
**Pull request by Naeralys**
Added jamtland county with the line 

`(5117,'Jämtland County',213,'SE','29',0,'SE-Z',63.283062,14.238281,'2022-11-04 09:51:51','2022-11-04 09:51:51',1,'Q103679')`

Id `5117` was incremented by from the last insert commit which was 5116

### CODE REVIEW

**Comment by dr5hn** [comment]
@Naeralys Thanks for the PR!

Can you please make those updates in the `world.sql` file rather than `states.sql` please?

**Comment by Naeralys** [comment]
> @Naeralys Thanks for the PR!
> 
> Can you please make those updates in the `world.sql` file rather than `states.sql` please?

Done!

**Comment by dr5hn** [comment]
@Naeralys Sorry to bother you again, can you please resolve the conflicts?

**Comment by Naeralys** [comment]
> @Naeralys Sorry to bother you again, can you please resolve the conflicts?
> 
> Also please discard the updates made to states.sql. Keep only world.sql changes.

@dr5hn Could you please get this merged?

**Review by dr5hn — APPROVED** [review]

**Pull request merged**
