### PR TITLE
Update cities benguela

### PR DESCRIPTION
**Pull request by NzongoPedro**
@AOSCODE
Team: Debugrs

New cities of Benguela City

@dr5hn

### CODE REVIEW

**Comment by NzongoPedro** [comment]
> @AOSCODE
> Team: Debugrs
> 
> New cities of Benguela City

@dr5hn

**Review by NzongoPedro — COMMENTED** [review]
@aoscode 
Team: Debuggers

New Benguela citities was add.
Please check it

**Review by NzongoPedro — COMMENTED** [review]
@aoscode 
Team: Debuggers

New Benguela citities was add.
Please check it

**Comment by dr5hn** [comment]
@NzongoPedro Thank you for the PR. Before I proceed with the data review, could you please populate the fields for created_at, updated_at, flag, and wikiDataId?

**Comment by NzongoPedro** [comment]
Yes, I will

A domingo, 22/10/2023, 14:31, Darshan Gada ***@***.***>
escreveu:

**Review by NzongoPedro — COMMENTED** [review]
@dr5hn Salut. 
New revision: I added the fields that were missing in my last PR

**Review by NzongoPedro — COMMENTED** [review]
fields was add

**Review by NzongoPedro — COMMENTED** [review]
Please check

**Comment by NzongoPedro** [comment]
HI, Can you can Review please?

Nzongo pedro ***@***.***> escreveu no dia domingo, 22/10/2023
à(s) 15:54:

**Review by NzongoPedro — COMMENTED** [review]
I need Your Feedback
@dr5hn

**Review by dr5hn — APPROVED** [review]

**Pull request merged**
