### PR TITLE
fix: add alimosho city to lagos state, nigeria

### PR DESCRIPTION
**Pull request by laurentcodes**
added a new city to lagos, nigeria
i want to know if i added this correctly before i proceed to add more, thanks.

### CODE REVIEW

**Comment by dr5hn** [comment]
@laurentcodes Thanks for the PR!

Can you please move your entry to very end of the `world.sql` and make sure to assign a ID (`last_id + 1`) to that newly added row?

**Comment by laurentcodes** [comment]
@dr5hn sure! will do that.

**Comment by laurentcodes** [comment]
@dr5hn, i have moved the entry to the end of the world.sql file and set an id (23), please check if correct

**Comment by dr5hn** [comment]
@laurentcodes You have moved to `subregions` table, can you please move it to `cities` table?

**Comment by laurentcodes** [comment]
@dr5hn i just did, please recheck, last entry under cities if that's correct

**Comment by laurentcodes** [comment]
@dr5hn fixed

**Review by dr5hn — APPROVED** [review]

**Pull request merged**
