### PR TITLE
Added town Adra, West Bengal, India

### PR DESCRIPTION
**Pull request by apexdivision**
Added town Adra, West Bengal, India

### CODE REVIEW

**Comment by dr5hn** [comment]
@nirjhareswar Thanks for the PR. 👍🏼 

However, if you can export the dump using PHPMyAdmin and MySQL, that will be great. Cause I see lots of changes.

**Comment by apexdivision** [comment]
@dr5hn Even I see that, surprisingly I used mysqldump on Mac. Should have just affected only header section and the respective record in concern. What I will do, will edit the file manually and commit.
Thanks!

**Comment by dr5hn** [comment]
@apexdivision Sorry for the delayed response, yes please if you can edit and manually commit this small change, that will be great!

Thanks for your help!

**Comment by dr5hn** [comment]
@apexdivision Would you mind re-adding the city manually to world.sql?

**Comment by apexdivision** [comment]
My apologies for the delay. Will do soon. In fact I have added a few more too.
Thank you for understanding

**Pull request closed without merging**
