### PR TITLE
Correction State OD City Bhubaneswar

### PR DESCRIPTION
**Pull request by Jayesh-Mahato**
Updated after latest pull.

### CODE REVIEW

**Comment by dr5hn** [comment]
@Jayesh-Mahato Can you please remove `states.sql` and `cities.sql` updates? As those files are auto generated.

**Review by Jayesh-Mahato — COMMENTED** [review]
@dr5hn  Removed cities.sql and states.sql

**Comment by dr5hn** [comment]
@Jayesh-Mahato Only discard the updates and not delete the file.

**Comment by Jayesh-Mahato** [comment]
Sorry. Updated another PR.

**Pull request closed without merging**
