### PR TITLE
Fix translations languages

### PR DESCRIPTION
**Pull request by mtsfer**
Reference: #868

Also fixes korean language code. The correct one is "ko".

Closes: #854

### CODE REVIEW

**Comment by dr5hn** [comment]
@mtsfer i think it should be

`zh-cn` and `ko-kr` respectively.

zh is the parent language code and cn is sub language code.

**Comment by mtsfer** [comment]
@dr5hn I've found [this discussion](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/250) about Chinese variations, and `zh-CN` is indeed the better option.

However, I wasn't able to find any reliable resource about ko-KR. Based [here](https://html-shark.com/HTML/LanguageCodes.htm), ko is the standard Korean, ko-KP is from North Korea and ko-KR is from South Korea.

Defaulting to ko while not sure which variation is being used on Korean translations wouldn't be a safer move here?

**Comment by dr5hn** [comment]
@mtsfer Could you please rebase you branch and resolve conflicts?

**Comment by mtsfer** [comment]
@dr5hn Sorry for the late reply. I'm working on this right now

**Review by dr5hn — APPROVED** [review]

**Comment by adevade** [comment]
@dr5hn @mtsfer This PR broke the `currency_symbol` for a couple of countries using `kr`. It now says `ko` instead of `kr` as it should be, and was before.

- Sweden (ID 213)
- Iceland (ID 100)
- Norway (ID 165)
- Bouvet Island (ID 30)
- Svalbard and Jan Mayen Islands (ID 211)

**Pull request merged**
