### PR TITLE
Update SQL Nigerian > Abuja Cities

### PR DESCRIPTION
**Pull request by bensonarafat**
Updated Abuja cities to the SQL world and cities. 
All these were missing at the first DB. 
thanks

### CODE REVIEW

**Comment by w01ki3** [comment]
While checking the added lines, I noticed that the wikidataid part is the same in all of them. Why ?

**Comment by bensonarafat** [comment]
> While checking the added lines, I noticed that the wikidataid part is the same in all of them. Why ?

Oh, my bad.. 
I just updated it with their vikidataid 
thanks for pointing it out.

**Comment by bensonarafat** [comment]
thank you

**Comment by dr5hn** [comment]
@bensonarafat Thanks for your efforts. Really appreciate it.

Can you please rebase the PR and also remove the `cities.sql`?

**Comment by dr5hn** [comment]
@bensonarafat Since I've incorporated your changes into PR #578, I will now be closing it. Thank you for your contributions.

**Comment by bensonarafat** [comment]
cool 
Thanks @dr5hn

**Pull request closed without merging**
