### PR TITLE
i have minimized the size of json files more than a half 

### PR DESCRIPTION
**Pull request by rasmi-aw**
i have minimized the size of json files more than a half

### CODE REVIEW

**Comment by WikiRik** [comment]
I don't think this is something that should be merged. It removes all readability from the JSON files. It also removes the reference to Israël which is a recognized country by the UN, regardless of political opinion. Finally, it adds files from the `.idea` folder but that's a small issue.

**Comment by seuros** [comment]
I agree . This is de-optimization and removing a country in a snicky way is not nice at all.

**Comment by rasmi-aw** [comment]
Well if taking someone's land and naming it a country, then killing the owners fits your life style, then it will never be accepted, the truth is the truth, the readability has to be bad to decrease the file size to use it in github api, what's the point of having a json with all countries, meanwhile you can't use it in a reall app ?.

**Comment by seuros** [comment]
Bravo! You fixed the middle-east issue with a PR.  Next, fix the conflict between 🇺🇦  and 🇷🇺 .

**Comment by jcalfee** [comment]
I here you @rasmi-aw .. You might want to look into all the "private" law groups that are springing up everywhere.  This is very different from the "public" legal system, it is really based on principal, easy to use, and in our favor.  We have our own tweaks to the ISO standard but it is based on well documented jurisdictional fraud which I suspect is involved in the case you mention.  We go over the research and the higher law.  An ISO standard that matches the systems out there is still useful even if we don't agree with it so that kind of thing may be better in the private and eventually into another database people can use.

**Comment by dr5hn** [comment]
@rasmi-aw 

Thanks for your PR 👍🏼 

I respect your patriotism, but Github is a place where we all unite ourselves, irrespective of country, race, religion, ethnicity, gender and sex. When you're on Github everyone is equal.

I liked the compression feature, but it's not something suitable for everyone. I need to think more about this and come up with a solution suitable for everyone out here.

For now, I will be closing your PR!

☮️ ✌🏼 Peace

**Pull request closed without merging**
